### ISSUE TITLE
graphql issue

### ISSUE THREAD

**Issue by umxr** [smakosh/gatsby-portfolio-dev#1]
Getting this issue, not sure why. ive created a .env file and added my personal github token

<img width="725" alt="screenshot 2018-12-27 at 21 59 05" src="https://user-images.githubusercontent.com/20203468/50495713-c8783e00-0a22-11e9-903c-b8f5408bb33e.png">

**Comment by smakosh** [comment]
Interesting, can you run `yarn reset && yarn start`, I used your username and managed to fetch your repositories without any issues.

**Comment by smakosh** [comment]
Ok I found what's causing that issue, my mistake I thought creating `.env` file is like `.env.development` but it seems it doesn't recognize the `.env` env variables, I'll update the docs.

Just rename your `.env` file to `.env.development` and everything should work fine

**Comment by twhite96** [comment]
Still getting this error and I have renamed the `.env` files.

**Comment by smakosh** [comment]
to `.env.development`? and did you place the env variables?

**Comment by twhite96** [comment]
>to `.env.development`? and did you place the env variables?

@smakosh yes. Just the GitHub token.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smakosh** [comment]
weird, is it open source? if so can you send me the link to your repository

**Comment by twhite96** [comment]
Yeah sure. https://github.com/twhite96/gatsby-portfolio-dev

**Comment by smakosh** [comment]
Just cloned and works fine, can you make sure to name the file exactly as `.env.development` and pass in this single env var with the right GitHub token:

```
GITHUB_TOKEN=xxxxxx
```

Run `yarn reset` then `yarn start`

**Comment by twhite96** [comment]
> Just cloned and works fine, can you make sure to name the file exactly as `.env.development` and pass in this single env var with the right GitHub token:
> 
> ```
> GITHUB_TOKEN=xxxxxx
> ```
> 
> Run `yarn reset` then `yarn start`

Yeah I've _done just that_.

**Comment by smakosh** [comment]
Pretty weird, works fine for me and for others who I asked to test

**Comment by smakosh** [comment]
Hey @twhite96 a fix has been pushed from one of Gatsby's members, you might want to give it a shot again

**Comment by jinoantony** [comment]
In my case the github token provided in env file was wrong. It works fine when I corrected it.
