### ISSUE TITLE
Issue building due to 'sharp'

### ISSUE THREAD

**Issue by zacharyparrish** [smakosh/gatsby-portfolio-dev#10]
I'm getting the below error when trying to set up this repo. I'm following all the prerequisites, and upon running `npm run start` this happens. 

![image](https://user-images.githubusercontent.com/7647623/66605935-a6494a00-eb76-11e9-96cf-ddc0d0d4dc89.png)

**Comment by smakosh** [comment]
That's a common issue with sharp module, you can solve it by removing yarn.lock and your node_modules folder and then run `yarn`, if it is still occurring run `npm rebuild`

**Comment by aech12** [comment]
tried that, didn't work

I deleted the whole
{
			resolve: 'gatsby-plugin-favicon',
			options: {},
},
from gatsby-config.js because of the icon warning (lol)

yarn cache clean, .cache folder deleted, yarn start worked

**Comment by smakosh** [comment]
Unfortunately it's an issue from a Gatsby plugin `sharp`
