### ISSUE TITLE
Deployment to Netlify fails at build

### ISSUE THREAD

**Issue by bingr001** [smakosh/gatsby-portfolio-dev#12]
I clicked on the try this starter on Netlify.
It begins the build process but then it fails.
The error happens at 10:12:45 AM
Below the error log:

10:11:10 AM: Build ready to start
10:11:16 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
10:11:16 AM: build-image tag: v3.3.2
10:11:16 AM: buildbot version: a2bab682ae0761baa4d123ebd00c57be933655dc
10:11:16 AM: Fetching cached dependencies
10:11:16 AM: Failed to fetch cache, continuing with build
10:11:16 AM: Starting to prepare the repo for build
10:11:16 AM: No cached dependencies found. Cloning fresh repo
10:11:16 AM: git clone https://github.com/smakosh/gatsby-portfolio-dev
10:11:17 AM: Preparing Git Reference refs/heads/master
10:11:18 AM: Starting build script
10:11:18 AM: Installing dependencies
10:11:18 AM: Attempting node version 'v12.13.0' from .nvmrc
10:11:19 AM: Downloading and installing node v12.13.0...
10:11:19 AM: Downloading https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.xz...
10:11:19 AM: 
###############################
10:11:19 AM:                             43.4%
10:11:19 AM: 
##################################
10:11:19 AM: ###################################### 100.0%
10:11:20 AM: Computing checksum with sha256sum
10:11:20 AM: Checksums matched!
10:11:22 AM: Now using node v12.13.0 (npm v6.12.0)
10:11:22 AM: Attempting ruby version 2.6.2, read from environment
10:11:24 AM: Using ruby version 2.6.2
10:11:24 AM: Using PHP version 5.6
10:11:24 AM: Started restoring cached node modules
10:11:24 AM: Finished restoring cached node modules
10:11:24 AM: Installing NPM modules using NPM version 6.12.0
10:11:32 AM: npm
10:11:32 AM:  WARN
10:11:32 AM:  deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
10:12:25 AM: > sharp@0.23.2 install /opt/build/repo/node_modules/gatsby-plugin-manifest/node_modules/sharp
10:12:25 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
10:12:26 AM: info
10:12:26 AM:  sharp
10:12:26 AM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
10:12:28 AM: > sharp@0.23.2 install /opt/build/repo/node_modules/gatsby-plugin-sharp/node_modules/sharp
10:12:28 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
10:12:28 AM: info
10:12:28 AM: sharp
10:12:28 AM:  Using cached /opt/buildhome/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
10:12:29 AM: > sharp@0.23.2 install /opt/build/repo/node_modules/gatsby-transformer-sharp/node_modules/sharp
10:12:29 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
10:12:29 AM: info
10:12:29 AM:  sharp
10:12:29 AM:  Using cached /opt/buildhome/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
10:12:30 AM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
10:12:30 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
10:12:31 AM: info
10:12:31 AM: sharp
10:12:31 AM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@babel/polyfill/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
10:12:33 AM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
10:12:33 AM: > https://opencollective.com/core-js 
10:12:33 AM: > https://www.patreon.com/zloirock 
10:12:33 AM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@gatsbyjs/relay-compiler/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/bmp/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/core/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/custom/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/gif/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/jpeg/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:33 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-blit/node_modules/core-js
10:12:33 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-blur/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-color/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-contain/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-cover/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-crop/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-displace/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-dither/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-flip/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-gaussian/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-invert/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:34 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-mask/node_modules/core-js
10:12:34 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-normalize/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-print/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-resize/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-rotate/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugin-scale/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/plugins/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/png/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/tiff/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/types/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/@jimp/utils/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:35 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
10:12:35 AM: > node postinstall || echo "ignore"
10:12:36 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/favicons-webpack-plugin/node_modules/core-js
10:12:36 AM: > node postinstall || echo "ignore"
10:12:36 AM: > core-js@3.4.0 postinstall /opt/build/repo/node_modules/favicons/node_modules/core-js
10:12:36 AM: > node postinstall || echo "ignore"
10:12:36 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/gatsby/node_modules/core-js
10:12:36 AM: > node postinstall || echo "ignore"
10:12:36 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/jimp/node_modules/core-js
10:12:36 AM: > node postinstall || echo "ignore"
10:12:36 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/potrace/node_modules/core-js
10:12:36 AM: > node postinstall || echo "ignore"
10:12:36 AM: > core-js@2.6.10 postinstall /opt/build/repo/node_modules/relay-runtime/node_modules/core-js
10:12:36 AM: > node postinstall || echo "ignore"
10:12:37 AM: > gatsby-telemetry@1.1.35 postinstall /opt/build/repo/node_modules/gatsby-telemetry
10:12:37 AM: > node src/postinstall.js
10:12:37 AM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
10:12:37 AM: > node lib/install.js
10:12:38 AM:   ✔ cwebp pre-build test passed successfully
10:12:38 AM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
10:12:38 AM: > node lib/install.js
10:12:38 AM:   ✔ mozjpeg pre-build test passed successfully
10:12:38 AM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
10:12:38 AM: > node lib/install.js
10:12:38 AM:   ✔ pngquant pre-build test passed successfully
10:12:39 AM: > gatsby-cli@2.8.8 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
10:12:39 AM: > node scripts/postinstall.js
10:12:39 AM: > gatsby@2.17.10 postinstall /opt/build/repo/node_modules/gatsby
10:12:39 AM: > node scripts/postinstall.js
10:12:39 AM: > styled-components@4.4.1 postinstall /opt/build/repo/node_modules/styled-components
10:12:39 AM: > node ./scripts/postinstall.js || exit 0
10:12:39 AM: Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
10:12:40 AM: npm notice created a lockfile as package-lock.json. You should commit this file.
10:12:40 AM: npm WARN
10:12:40 AM:  eslint-config-react-app@5.0.2 requires a peer of eslint@6.x but none is installed. You must install peer dependencies yourself.
10:12:40 AM: npm WARN
10:12:40 AM:  tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
10:12:40 AM: npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
10:12:40 AM: npm
10:12:40 AM: WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
10:12:40 AM: npm WARN optional
10:12:40 AM:  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
10:12:40 AM: npm
10:12:40 AM: WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:12:40 AM: npm WARN optional
10:12:40 AM:  SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.1 (node_modules/chokidar/node_modules/fsevents):
10:12:40 AM: npm WARN
10:12:40 AM:  notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:12:40 AM: added 2151 packages from 1031 contributors and audited 26421 packages in 75.655s
10:12:40 AM: found 0 vulnerabilities
10:12:41 AM: NPM modules installed
10:12:41 AM: Started restoring cached go cache
10:12:41 AM: Finished restoring cached go cache
10:12:41 AM: unset GOOS;
10:12:41 AM: unset GOARCH;
10:12:41 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
10:12:41 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
10:12:41 AM: go version >&2;
10:12:41 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
10:12:41 AM: go version go1.12 linux/amd64
10:12:41 AM: Installing missing commands
10:12:41 AM: Verify run directory
10:12:41 AM: Executing user command: gatsby build
10:12:43 AM: success open and validate gatsby-configs - 0.021s
10:12:43 AM: success load plugins - 0.714s
10:12:45 AM: success onPreInit - 0.002s
10:12:45 AM: success delete html and css files from previous builds - 0.010s
10:12:45 AM: success initialize cache - 0.031s
10:12:45 AM: success copy gatsby files - 0.030s
10:12:45 AM: success onPreBootstrap - 0.010s
10:12:45 AM: error "gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:
10:12:45 AM: Response not successful: Received status code 401
10:12:45 AM: 
10:12:45 AM:   ServerError: Response not successful: Received status code 401
10:12:45 AM:   
10:12:45 AM:   - index.js:23 Object.exports.throwServerError
10:12:45 AM:     [repo]/[apollo-link-http-common]/lib/index.js:23:17
10:12:45 AM:   
10:12:45 AM:   - index.js:48 
10:12:45 AM:     [repo]/[apollo-link-http-common]/lib/index.js:48:21
10:12:45 AM:   
10:12:45 AM:   - task_queues.js:93 processTicksAndRejections
10:12:45 AM:     internal/process/task_queues.js:93:5
10:12:45 AM:   
10:12:45 AM: 
10:12:45 AM: not finished source and transform nodes - 0.276s
10:12:45 AM: Skipping functions preparation step: no functions directory set
10:12:45 AM: Caching artifacts
10:12:45 AM: Started saving node modules
10:12:45 AM: Finished saving node modules
10:12:45 AM: Started saving pip cache
10:12:45 AM: Finished saving pip cache
10:12:45 AM: Started saving emacs cask dependencies
10:12:45 AM: Finished saving emacs cask dependencies
10:12:45 AM: Started saving maven dependencies
10:12:45 AM: Finished saving maven dependencies
10:12:45 AM: Started saving boot dependencies
10:12:45 AM: Finished saving boot dependencies
10:12:45 AM: Started saving go dependencies
10:12:45 AM: Finished saving go dependencies
10:12:47 AM: Error running command: Build script returned non-zero exit code: 1
10:12:47 AM: Failing build: Failed to build site
10:12:47 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
10:12:47 AM: Finished processing build request in 1m31.961372722s

**Comment by smakosh** [comment]
check readme file and follow the steps, you forgot to add the env variables to Netlify.

**Comment by byteshiva** [comment]
This is for future reference,
To make this site work in netlify,  the below variable needs to be added in Netlify.

```
GITHUB_TOKEN
SITE_RECAPTCHA_KEY
SITE_RECAPTCHA_SECRET
```
