### ISSUE TITLE
Some missing assets.

### ISSUE THREAD

**Issue by Lukortech** [smakosh/gatsby-portfolio-dev#13]
While looking at the portfolio online I've spotted that some assts don't load and throw 404.
![Zrzut ekranu z 2019-11-18 05-23-49](https://user-images.githubusercontent.com/26508593/69024580-a6353900-09c3-11ea-8fd6-b0ab363cd703.png)

Just a friendly poke about it.

**Comment by smakosh** [comment]
Good catch @Lukortech 
I'll fix it once I move the website to Zeit Now.

**Comment by smakosh** [comment]
Fixed here: https://github.com/smakosh/gatsby-portfolio-dev/pull/16
