### ISSUE TITLE
Unable to fetch result from queries

### ISSUE THREAD

**Issue by shakti97** [smakosh/gatsby-portfolio-dev#18]
![ErrorPortfolio](https://user-images.githubusercontent.com/30585570/71588514-cf5ef280-2b47-11ea-8e20-dd7c742e85a4.png)
is it the problem with gatsby? @smakosh 
I just change the access token for github in development mode.

**Comment by smakosh** [comment]
Can you send me a link to your repository to debug?

**Comment by shakti97** [comment]
https://github.com/shakti97/Portfolio

**Comment by smakosh** [comment]
You can get your access token from here: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
