### ISSUE TITLE
Cannot read property 'repositories' of null

### ISSUE THREAD

**Issue by natterstefan** [smakosh/gatsby-portfolio-dev#2]
Hi @smakosh,

thanks for the effort you invested in your template. Looks very promising! Though I have troubles creating (`yarn build`) the site (with the latest commit https://github.com/smakosh/gatsby-portfolio-dev/commit/b9a434e43262f98f0c164dd7bc7733c1e17905e1). FTR, `yarn start` works without any issue.

![image](https://user-images.githubusercontent.com/1043668/50658174-cbca7700-0f98-11e9-94b9-95c7f735a965.png)

What am I missing? Is it related to the scope of my Github token? Maybe my issue is related to the scope I have chosen.

My `.env.development` looks something like

```
GITHUB_TOKEN=2fa....
```

And I have changed this https://github.com/smakosh/gatsby-portfolio-dev/blob/master/src/components/landing/Projects/index.jsx#L13 to:

```js
export const Projects = () => (
	<StaticQuery
		query={graphql`
      {
        github {
          repositoryOwner(login: "natterstefan") {
            repositories(
              first: 8
              orderBy: { field: STARGAZERS, direction: DESC }
            ) {
              edges {
                node {
                  id
                  name
                  url
                  description
                  stargazers {
                    totalCount
                  }
                  forkCount
                }
              }
            }
          }
        }
      }
    `}
		render={({
			github: {
				repositoryOwner: {
					repositories: { edges },
				},
			},
		}) => (
```

I feel like I am missing just a small piece. Thank you!

**Comment by natterstefan** [comment]
Hi @smakosh, I figured it out. I missed creating a `.env.production` before building the site. Maybe you add this to the README.md as well as a hint for others.

https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript

**Comment by smakosh** [comment]
It has been added 😄 before already

**Comment by smakosh** [comment]
Check: https://github.com/smakosh/gatsby-portfolio-dev#prerequisites

**Comment by smakosh** [comment]
Oh sorry, you meant building locally! sure I'll add it to the readme file, thanks!

**Comment by natterstefan** [comment]
Yes, I mean to build it locally. Thank you @smakosh!
