### ISSUE TITLE
Unable to build: Build failed

### ISSUE THREAD

**Issue by nguptaa** [smakosh/gatsby-portfolio-dev#31]
Unable to build.

Screenshot:-

![Screenshot 2020-06-22 at 4 13 10 PM](https://user-images.githubusercontent.com/22504975/85277678-80b16600-b4a3-11ea-9f70-339d35608065.png)

**Comment by smakosh** [comment]
Please read the documentation as you forgot your env variable with your GitHub token

**Comment by nguptaa** [comment]
> Please read the documentation as you forgot your env variable with your GitHub token

I've added all necessary tokens in .env.development

It's working perfectly fine on localhost( yarn start) however fails to build.

**Comment by nguptaa** [comment]
Worked. I forgot to add .env.production
