### ISSUE TITLE
How to get the Formium endpoint?

### ISSUE THREAD

**Issue by lcofre** [smakosh/gatsby-portfolio-dev#37]
**Describe the bug**
First of all: Amazing starter! It's just an awesome work you did here.

This is more a heads up really. If I'm not missing something, there is no easy way to grab the endpoint on the Formium site.
After creating a form I have to go to "View & Share your form" where I get a URL of the form *https://forms.formium.io/f/<MY_FORM_ID>*. I go to that URL and with the browser developer tools open, send a form. In the network tab, I find a POST request to the URL *https://api.formium.io/v1/form/<MY_FORM_ID>/submit*. That last one is the one to put on the GATSBY_PORTFOLIO_RECAPTCHA_KEY environment variable.

I may be missing the proper way to grab the endpoint, but if Formium UI changed I hope this is helpful to you.

Thanks very much!

**Comment by smakosh** [comment]
Hey @lcofre 👋 

Thanks for the positive feedback, I appreciate it!

I should probably include a video how to create an account, form and grab the Formium url on Formium's website, will work on that during the weekends for sure!

I think you're mistaken the Google recaptcha key env variable with Formium (Formik) env variable

Check the env template file [here](https://github.com/smakosh/gatsby-portfolio-dev/blob/master/.env.development.template#L2)

If you're still having issues deploying your portfolio, I'm open to sync with you on a call to help you

**Comment by lcofre** [comment]
Oh yes, sorry. I meant to say the GATSBY_PORTFOLIO_FORMIK_ENDPOINT environment variable.

**Comment by smakosh** [comment]
Yes that's correct, you should have the Formium url as the value of that env variable
