### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by Now-Sprouting** [smakosh/gatsby-portfolio-dev#39]
### Hello, Boss, I am a rookie. May I ask that this mistake has happened since I 'gatsby develop' Do you know how to resolve it

There was an error in your GraphQL query:

Cannot query field "github" on type "Query".

If you don't expect "github" to exist on the type "Query" it is most likely a typo.
However, if you expect "github" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "github" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: D:/VSCodeProject/Gatsby-blog/resume-blog/src/components/landing/Projects/index.jsx

**Comment by smakosh** [comment]
You most likely forgot to include a GitHub token as mentioned on the docs, if that type wasn't available, the build would fail when deploying to Vercel or when running `gatsby develop` locally.

But I will re-check just in case, thanks.

**Comment by Now-Sprouting** [comment]
Ok, thank you very much indeed

**Comment by Now-Sprouting** [comment]
Feel the website you designed is very handsome
