### ISSUE TITLE
gatsby-plugin-favicon

### ISSUE THREAD

**Issue by carriepresley** [smakosh/gatsby-portfolio-dev#42]
Everytime I try to run the development server I get an error with the favicon-plugin? Help. I'm a newbie, but I've been troubleshooting for a while and even after installing the plugin, I get the same error?

'There was a problem loading plugin "gatsby-plugin-favicon". Perhaps you need to install its package?
Use --verbose to see actual error.

 ERROR #10226  CONFIG'

**Comment by smakosh** [comment]
I deleted the node modules locally and ran `yarn && yarn start` and everything seems to be working fine, can you share your node version?

**Comment by smakosh** [comment]
Could you share your repository and I'll be able to help debug your issue

**Comment by carriepresley** [comment]
Thank you smakosh! I just deleted and made a new one, thank you in advance!

**Comment by smakosh** [comment]
Could you email me the env variables? or feel free to send them via [Keybase](https://keybase.io/app)

**Comment by smakosh** [comment]
I cloned your example, used my env variables and it seems to be working fine, going to close this issue for now. Feel free to re-open if the issue is still persistent

**Comment by carriepresley** [comment]
Thank you smakosh! I'll keep working on it... I appreciate you!

**Comment by smakosh** [comment]
Sure! anytime
