### ISSUE TITLE
Problem with deployment on Netlify

### ISSUE THREAD

**Issue by lindjacob** [smakosh/gatsby-portfolio-dev#44]
I have been reading all previous bug reports, the readme.md and the resource you suggested on "Integrating Netlify Form Handling in Gatsby". 

YET, I cannot figure out how to solve the issue Netlify keeps throwing at me.
It works locally and I have added the tokens for reCAPTCHA to the Netlify environment.

Here is an image of my deployment error:
![image](https://user-images.githubusercontent.com/46849623/109726101-68f1bc00-7bb2-11eb-8154-d68ce44cfa72.png)

I would greatly appreciate any help you can provide!

**Comment by smakosh** [comment]
Hey @lindjacob that's the GitHub API token that you forgot to include in your env variables

**Comment by lindjacob** [comment]
Hi smakosh,
I really appreciate that you take your time to write me!

I believe it should be done. But have I made a mistake then?

This is my local .env.development:
![image](https://user-images.githubusercontent.com/46849623/109796384-62962b00-7c18-11eb-88f1-0234b4556ff3.png)
I have even tried removing GATSBY_PORTFOLIO and writing the keys in two different ways.

At Netlify, I have added the reCAPTCHA_KEYs:
![image](https://user-images.githubusercontent.com/46849623/109796876-fa941480-7c18-11eb-8656-45fdc7c91ecd.png)
Should I also add a GITHUB_TOKEN there, even though my Netlify is synced with Github?

And if so, how do I make sure that my build has access to it, like I read I had to do with the reCAPTCHA_KEY:
![image](https://user-images.githubusercontent.com/46849623/109797213-71311200-7c19-11eb-9630-b862548971f0.png)


Thank you again, for any help provided!

**Comment by smakosh** [comment]
You need to add the GitHub env variable to Netlify as well

**Comment by smakosh** [comment]
![Screen Shot 2021-03-03 at 10 05 37](https://user-images.githubusercontent.com/20082141/109851015-01fef200-7c08-11eb-8b5a-b0c582c40b57.png)

**Comment by lindjacob** [comment]
Thanks again for your time smakosh.
I had forgotten to copy the Netlify branch into the folder...
(https://github.com/smakosh/gatsby-portfolio-dev/tree/netlify)

Now it's time to play around with it.
