### ISSUE TITLE
Next.js version?

### ISSUE THREAD

**Issue by karlhorky** [smakosh/gatsby-portfolio-dev#45]
Hi there, first of all, thanks for this starter, very cool!

**Is your feature request related to a problem? Please describe.**

It would be nice to be able to use this template with Next.js

**Describe the solution you'd like**

A version of the template in Next.js

**Describe alternatives you've considered**

Having the community create this Next.js version

**Comment by smakosh** [comment]
Hey @karlhorky, yeah I was planning to create a Next js version of this portfolio but couldn't get some free time to do it, if you or anyone within the community manages to create it, I'll be happy to contribute in any way I could. In the meanwhile I'll do my best to spare some free time to build it.

**Comment by smakosh** [comment]
There you go: https://github.com/smakosh/next-portfolio-dev
