### ISSUE TITLE
Form doesn't work

### ISSUE THREAD

**Issue by mike-source** [smakosh/gatsby-portfolio-dev#49]
There seems to be some confusion between Formik & Formium integration going on?

Am I missing something? Sending any POST request to "http://localhost:8000/api/contact" will just return a 404.

Currently pressing the submit on the form always fails the try/catch in the ContactForm component.

**Comment by smakosh** [comment]
run `vercel dev` to run your serverless function, see: [Docs](https://vercel.com/docs/serverless-functions/introduction) for more details

**Comment by mike-source** [comment]
After running `vercel dev` I can submit to the Formium form I created by manually creating a POST request (in postman) with something like the following payload:

<code>
{
  "name":"name", 
  "email":"test@test.com", 
  "message":"test"
}
</code>

But when I try to submit the form (with the same data entered for the fields) it fails and displays the `alert("Something went wrong, please try again!");` from line 56 of the ContactForm component.

If you output the error by e.g. changing to `alert(err)` it gives "Error: Network Error".

I also deployed to Vercel and pressing submit on the form when hosted on a Vercel environment leads to the recaptcha failing:
"ERROR for site owner: Invalid key type"

Environment variables are filled out with a Google recaptcha v3 key, your docs didn't specify which key to use, Google provide a client side 'site' key, and a server site 'secret' key, I tried every combination of both, locally and on the Vercel deploy.

Your readme also says to include a Formik endpoint, but then your .env template says Formium.

**Comment by mike-source** [comment]
Actually, I solved the "Error: Network Error" and got it working locally, the issue was on line 40 of ContactForm/index.jsx, where you have hard coded the localhost uri in the submit handler to be "http://localhost:8000/api/contact", running `vercel dev` for me hosted it on localhost:3000

Hopefully that helps someone!

I'm still stuck on getting the recaptcha working on the Vercel hosted version... I still get "ERROR for site owner: Invalid key type"

Thanks for your help!

**Comment by smakosh** [comment]
Hey @mike-source, I will update the docs accordingly and also set that port to be 8000.

For the issue you're having, you will need to enable your domain name from the Recaptcha service so that you will be able to use the Google Recaptcha

**Comment by mike-source** [comment]
@smakosh hmmm, I did enable the vercel domain (the appname.vercel.app one) in the Recaptcha settings for Google but it seems to still give the same error "Invalid Key Type". The environment variable is added in the Vercel web settings and in the .env file locally. Locally I don't get the Recaptcha error though.

It would be helpful if you could specify in the readme which key to use from Google Recaptcha... (client side or server side, I assumed client side but tried both).

**Comment by smakosh** [comment]
Just client side as mentioned in the README file. I'll be taking a deeper look at this

**Comment by smakosh** [comment]
Hey @mike-source can you specify which Recaptcha version are using?

**Comment by mike-source** [comment]
reCAPTCHA type:v3

**Comment by smakosh** [comment]
That might be the issue, this project is using the v2, try that one and let me know if you're still having the same issue

**Comment by mike-source** [comment]
Thanks, I gave it a try with a v2 key but get the same error unfortunately.

**Comment by smakosh** [comment]
Want to jump into Discord to help you resolve this?

**Comment by mike-source** [comment]
Sure if you like, what is your discord?

**Comment by smakosh** [comment]
`Smakosh#7017`

**Comment by mike-source** [comment]
Okay, confirmed working now.

Remember:
- set the google recaptcha to be v2, and using the "I'm not a robot" checkbox
- update the url property in gatsby config /src/data/config.js to match the url of the vercel deploy

**Comment by smakosh** [comment]
Updated docs, thanks @mike-source!
