### ISSUE TITLE
Hello I created this  issue on the official gatsby plugin and I need help

### ISSUE THREAD

**Issue by udemezue01** [smakosh/gatsby-portfolio-dev#51]
I am going to drop a link to the full detail of the issue on Git please help me check it out

https://github.com/gatsbyjs/gatsby/discussions/32193

**Comment by smakosh** [comment]
You probably forgot to specify your env variables

**Comment by udemezue01** [comment]
It is well spelt out

**Comment by udemezue01** [comment]
Can you pull the code into your local computer

**Comment by smakosh** [comment]
Sure will do tonight

**Comment by smakosh** [comment]
Works fine, make sure to specify the env variables as mentioned in the README file
