### ISSUE TITLE
Clarification on Recaptcha key

### ISSUE THREAD

**Issue by dylanesque** [smakosh/gatsby-portfolio-dev#52]
Step 2 of the prerequisites states: 

"Grab a Google recaptcha key from Google Recaptcha", but there are two keys (one site key, and one secret key) that we're provided with upon recaptcha signup. 

Which of the keys are we supposed to plug into the `GATSBY_PORTFOLIO_RECAPTCHA_KEY` env var, the secret key or the site key?

**Comment by smakosh** [comment]
The site key
