### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by zacharyparrish** [smakosh/gatsby-portfolio-dev#7]
I'm getting this issue when I attempt to run `gatsby develop` on a fresh clone. I understand the first error to be related to my Github access token (I have yet to put that in), but I'm unsure of the second one

----

UNHANDLED REJECTION Type with name "File" does not exists

  Error: Type with name "File" does not exists

  - TypeStorage.js:44 SchemaComposer.get
    [portfolio]/[graphql-compose]/lib/TypeStorage.js:44:13

  - SchemaComposer.js:530 SchemaComposer.getAnyTC
    [portfolio]/[graphql-compose]/lib/SchemaComposer.js:530:19

  - schema.js:768 parentTypesToChildren.forEach
    [portfolio]/[gatsby]/dist/schema/schema.js:768:41

  - Map.forEach

  - schema.js:767 addConvenienceChildrenFields
    [portfolio]/[gatsby]/dist/schema/schema.js:767:25

  - schema.js:160 updateSchemaComposer
    [portfolio]/[gatsby]/dist/schema/schema.js:160:9

![image](https://user-images.githubusercontent.com/7647623/62143539-c7a7d300-b2b5-11e9-863d-c1b4f427ce54.png)

**Comment by smakosh** [comment]
the GitHub token is required for the build to succeed

**Comment by zacharyparrish** [comment]
I understand that the token is needed, but even after the token is created, I still get this error when trying to build. 

![image](https://user-images.githubusercontent.com/7647623/62224034-98f43000-b37b-11e9-8128-d0d186e1d326.png)
